app:
  name: User-Role-Service
  ip_address: 0.0.0.0
  port: 3000
  jwt_secret: afagewsagsdvshgbrdshnrdsf
  api_key: egesgsrhsndsrdshbdb

database:
  host: localhost
  port: 3306 
  user: root
  password: ""
  name: app